vich_uploader:
    db_driver: orm
    mappings:
        valuation_register:
            uri_prefix: /files/valuation_register
            upload_destination: '%kernel.project_dir%/public/data/valuation_register'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
