Accounts:
    FrontEndUsers:
      roleClass: App\Controller\UserAccounts\UserController
      actions: ["view","add","edit","delete","info","approve","decline"]
      key: users-accounts

    Roles:
      roleClass: App\Controller\UserAccounts\RoleController
      actions: ["view","add","edit","delete"]
      key: role-configuration


Configuration:
    Space:
      roleClass: App\Controller\Configuration\SpaceController
      actions: [ "view","add","edit","delete" ]
      key: space-configuration

    Tag:
      roleClass: App\Controller\Configuration\TagController
      actions: [ "view","add","edit","delete" ]
      key: tag-configuration
